apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ltyymp8ta-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ltyymp8ta-java-quarkus-gitops